# Generated by Django 5.0.6 on 2024-05-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_calc', '0002_rename_agent_name_order_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=250, verbose_name='Наименование траты')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма трат')),
                ('data_expense', models.DateField(auto_now_add=True, verbose_name='Когда потратил ?')),
            ],
            options={
                'verbose_name': 'Расходы',
                'verbose_name_plural': 'Расходы',
            },
        ),
    ]
