# Generated by Django 5.0.6 on 2024-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_calc', '0003_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
