# Generated by Django 5.0.6 on 2024-05-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_calc', '0004_alter_expenses_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Трата', 'verbose_name_plural': 'Расходы'},
        ),
    ]
