# Generated by Django 5.0.6 on 2024-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_calc', '0005_alter_expenses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Телефон заказчика'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='car',
            field=models.CharField(max_length=100, unique=True, verbose_name='Машина и гос.номер'),
        ),
    ]
