# Generated by Django 5.0.6 on 2024-05-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_calc', '0006_alter_agent_agent_phone_alter_worker_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
