# Generated by Django 5.0.6 on 2024-06-05 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_calc', '0007_alter_order_created_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('publish_data', models.DateField(default=django.utils.timezone.now, verbose_name='Дэдлайн')),
                ('comment', models.TextField(max_length=350, verbose_name='Комментарий:')),
                ('task_type', models.CharField(choices=[('1', 'Не важно'), ('2', 'Средне'), ('3', 'Важно')], max_length=100, verbose_name='Степень важности:')),
                ('task_status', models.CharField(choices=[('1', 'Не начал'), ('2', 'В процессе'), ('3', 'Выполнил')], max_length=100, verbose_name='Статус выполнения:')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
