# Generated by Django 5.0.6 on 2024-06-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_calc', '0008_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task_id',
            new_name='id',
        ),
    ]
